### ISSUE TITLE
Selenium grid chrome/firefox node timeout issue on Openshift master  v3.9.31 and Kubernetes Master: v1.9.1+

### ISSUE THREAD

**Issue by murthyganti** [ddavison/selenium-openshift-templates#12]
First of all, thanks for the templates. Based on instructions  We have created setup the selenium-hub and selenium-node-chrome/firefox nodes on Openshift. Hub can't creates sessions in nodes. Could u please let me why i am seeing this timeouts. I can post setup confing screenshots if needed

I can send requests to route i have created for the hub, for example:
http://selenium-hub-ue90-platformtest.apps.c1-ocp-dc1.dev.mycompanyname.com/wd/hub

I am seeing the following error in my console:

`chrome #01-2] WebDriverError: <html><body><h1>504 Gateway Time-out</h1>
[chrome #01-2] The server didn't respond in time.
[chrome #01-2] </body></html>
[chrome #01-2]`

In selenium-hub logs, I am seeing this error.
`
15:50:34.404 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [window-size=1900,1020]}, count: 1, idleTimeout: 3600, maxInstances: 2, shardTestFiles: true}
  | 15:50:34.404 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=3ed53258-b3c8-4650-a16a-8aa9a7346a57, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=1, platformName=LINUX, version=70.0.3538.110, applicationName=, platform=LINUX}
  | 15:50:34.913 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [window-size=1900,1020]}, count: 1, idleTimeout: 3600, maxInstances: 2, shardTestFiles: true}
  | 15:50:34.914 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=7cee7486-7de8-47fd-8988-d54cb490cec3, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=1, platformName=LINUX, version=70.0.3538.110, applicationName=, platform=LINUX}
  | 15:51:07.572 ERROR [RequestHandler.process] - Socket timed out for session ext. key 0e71f0a138523e0a6b494ad6e51c8fa9, timeout
  | 15:51:07.977 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [window-size=1900,1020]}, count: 1, idleTimeout: 3600, maxInstances: 2, shardTestFiles: true}
  | 15:51:07.978 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=48846111-8939-4230-9531-8784d0b316bd, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=1, platformName=LINUX, version=70.0.3538.110, applicationName=, platform=LINUX}
  | 15:51:08.101 ERROR [RequestHandler.process] - Socket timed out for session ext. key 227c6648bc7786be9e211a1f10e1a687, timeout
  | 15:51:37.990 INFO [RequestHandler.process] - Error forwarding the new session Error forwarding the request timeout
  | org.openqa.grid.internal.exception.NewSessionException: Error forwarding the request timeout
  | at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:94)
  | at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:114)
  | at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
  | at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  | at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
  | at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
  | at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
  | at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
  | at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
  | at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
  | at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
  | at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
  | at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
  | at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
  | at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
  | at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
  | at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
  | at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
  | at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
  | at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
  | at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
  | at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
  | at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
  | at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
  | at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
  | at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
  | at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
  | at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
  | at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
  | at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
  | at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
  | at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
  | at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.net.SocketTimeoutException: timeout
  | at okio.Okio$4.newTimeoutException(Okio.java:232)
  | at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
  | at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
  | at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
  | at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
  | at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
  | at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
  | at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
  | at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
  | at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
  | at okhttp3.RealCall.execute(RealCall.java:77)
  | at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
  | at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:422)
  | at org.openqa.grid.internal.TestSession.forward(TestSession.java:229)
  | at org.openqa.grid.web.servlet.handler.RequestHandler.forwardNewSessionRequestAndUpdateRegistry(RequestHandler.java:91)
  | ... 35 more
 
`

**Comment by sgraza** [comment]
i'm also experiencing the same issue. can someone pls help to check?

**Comment by ddavison** [comment]
by chance @murthyganti , if this is still an issue for you - what Selenium version are you attempting to use?

this project was created by me looong ago when i used to use openshift.  i haven't looked at the source in a while, but it's possible if you are using newer versions of `selenium/hub` or `selenium/node-*` images from [docker-selenium](https://github.com/seleniumhq/docker-selenium) it might be possible we changed, deleted, or added some variables. this project was tested with earlier versions of the images.  perhaps you should try fiddling witht he selenium versions.

`image: selenium/hub:3.1` for instance

###
